### ISSUE TITLE
What is Stem in Figure 3？

### ISSUE THREAD

**Issue by AI-student-wl** [zhanggang001/CEDNet#6]
This is a very excellent work, thank you for your efforts in this field. I have a small question that I don't quite understand. In Figure 3 on the third page of the paper, what is Stem? What is its structure? Or is it a regular convolution operation? Could you please tell me again and thank you for your excellent work!

**Comment by zhanggang001** [comment]
> This is a very excellent work, thank you for your efforts in this field. I have a small question that I don't quite understand. In Figure 3 on the third page of the paper, what is Stem? What is its structure? Or is it a regular convolution operation? Could you please tell me again and thank you for your excellent work!

Thanks for your attention to our work!  The stem is two 3x3 convolutions, with an intermediate channel of 32.
